name: PR Build

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: debug
        run: "echo app version: $APP_VERSION"

      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: dotnet build
        run: dotnet build --self-contained -r win-x64 -f net8.0 -c release
